### ISSUE TITLE
Maybe replace the staff group with an is_on_service_contract person attribute?

### ISSUE THREAD

**Issue by yohell** [neicnordic/experimental.neic.nordforsk.org#12]
I feel the staff group is ambiguous and hard to work into the people/activities structure.

**Comment by bast** [comment]
Do we need this information at all? I feel we don't need to display this.

**Comment by bast** [comment]
If we need it, then your suggestion is a good solution IMO.

**Comment by yohell** [comment]
Yes, because this how we communicate openly who we reimburse for travel etc. Very important to have that open, so that all from staff to line managers to PMs to POs to Dir to Kine have the same view of the situation, and what's the correct thing to do.

One comms channel, one place for the correct info.

⁣Sent from TypeApp ​

**Comment by bast** [comment]
Then :+1: for your suggestion.

**Comment by yohell** [comment]
61ad027
