### ISSUE TITLE
port news posts

### ISSUE THREAD

**Issue by yohell** [neicnordic/experimental.neic.nordforsk.org#14]

**Comment by yohell** [comment]
Added news, quick and dirty f534c99a9b3d0d7144c6fdb8de09a5c230817dd2.

**Comment by bast** [comment]
Looks good! I will give it a tiny CSS polishing.

**Comment by yohell** [comment]
Be my guest!
/Joel

⁣Sent from TypeApp ​

**Comment by bast** [comment]
CSS work postponed until we get the design so from my perspective this issue can be closed.
