### ISSUE TITLE
Outreach in activity page is now hardcoded

### ISSUE THREAD

**Issue by bast** [neicnordic/experimental.neic.nordforsk.org#21]
See https://github.com/neicnordic/neic.no/blob/094823328b8f9c8bc0/_includes/activity.html#L70.

I guess this should be somehow pulled from a calendar but I have no idea how this works: https://github.com/neicnordic/neic.no/blob/17d9743/_includes/activity.html#L91-L114.

Also please do not call functions "foo".

@yohell can you please look at that?

**Comment by yohell** [comment]
Sure.

~/foo/lol/

**Comment by bast** [comment]
One problem that we will have with the calendar is that markup is done in the js file which will not be the same markup as the new design - what i think we should do instead is that the gcal-events.js should not do any markup but return data and we should IMO loop over the data on the template site so that we have more control over markup and better abstraction.

**Comment by bast** [comment]
Now I also understand how it is done but am rather certain that with the current setup we will drive against a wall unless we abstract markup out of the js.

**Comment by yohell** [comment]
Agreed.

**Comment by yohell** [comment]
Better gcal.js pushed in 9562de2772c1db037.

Now doing rendering with Vuejs and ajax with jQuery.

**Comment by yohell** [comment]
No longer hardcoded in 55ca552.

**Comment by bast** [comment]
Where can I see a working example? Can you please post a link?

**Comment by bast** [comment]
Aha, Tryggve activity page seems to be a good example. Somehow I missed it earlier.

**Comment by bast** [comment]
Aha. Now I understand - outreach shows up on http://localhost:4000/activities/tryggve/ but not on http://127.0.0.1:4000/activities/tryggve/.

**Comment by bast** [comment]
I think this one is now solved. Thanks for that!
