### ISSUE TITLE
Hardcoded text in /about/ page

### ISSUE THREAD

**Issue by bast** [neicnordic/experimental.neic.nordforsk.org#23]
- [x] publications are hardcoded
- [x] "What is NeIC?" is repeated (click "read more")
- [x] "Our history" is repeated (click "read more")

**Comment by yohell** [comment]
Idk what you mean by "hardcoded" in this instance really, but with 0a07412 imho publications are not.

**Comment by bast** [comment]
OK then perhaps I misunderstood - ticking it off then.

**Comment by yohell** [comment]
Aha, no you are right. You are talking about the hypertall actual /about/ page, not the pages under /about/. I agree, those are hardcoded, and should probably be generated instead.

**Comment by bast** [comment]
Yes, exactly :-)

**Comment by bast** [comment]
Problem solved.
