### ISSUE TITLE
Creation and placement of calendar links

### ISSUE THREAD

**Issue by yohell** [neicnordic/experimental.neic.nordforsk.org#27]
This event has an anchorjs link next to its heading which displays on hover.

http://neic.no/activities/tryggve/#eudat-sensitive-data-meeting

I wanted to do the same but with a calendar icon, to edit the calendar. I stole the html that anchorjs generates and replaced the icon and url. 

Issues:

* Is there a better way to do it? For example anchorjs has some logic in it to know whether the icon be shown on hover or always (eg on touchscreens).
* I couldn't get the icon to display next to the heading, but it would always end up on the next line. So now I'm displaying it next to the date instead. Good/bad?

**Comment by bast** [comment]
Where/how can I see/try what you have implemented?
