### ISSUE TITLE
Is bullet lists the best way of displaying people?

### ISSUE THREAD

**Issue by yohell** [neicnordic/experimental.neic.nordforsk.org#3]
Should we have tables? Make them sortable by country?

**Comment by bast** [comment]
Now looks like a telephone book. I would sort by country and in addition also display a map à la https://software-carpentry.org/team/.

**Comment by yohell** [comment]
Country sort 6189560

**Comment by bast** [comment]
I like it. Closing. If we are unhappy later, we can always reopen or open a new issue.
