### ISSUE TITLE
Long names for organisations let people page look ugly

### ISSUE THREAD

**Issue by trz42** [neicnordic/experimental.neic.nordforsk.org#32]
See https://neic.no/people/

Either the design of that page should be changed to, e.g., single column, or we have to use short names/acronyms for organisations (and document a limit somewhere).

**Comment by bast** [comment]
Confirmed. We probably need a short and long affiliation version. I suggest we do not add more people before we fix this issue.

**Comment by bast** [comment]
It seems that this got fixed.
