### ISSUE TITLE
NeIC team includes other kinds of people

### ISSUE THREAD

**Issue by trz42** [neicnordic/experimental.neic.nordforsk.org#33]
For example, researchers, application experts, e-scientists, ...

**Comment by bast** [comment]
That is true but can you please be more specific of what page or data structure or source file is incomplete?

**Comment by trz42** [comment]
_includes/people.html lines 49-51

**Comment by bast** [comment]
Thanks! Now hopefully better.

**Comment by trz42** [comment]
yes
