### ISSUE TITLE
Faces and images are stretched on https://neic.no/news/

### ISSUE THREAD

**Issue by bast** [neicnordic/experimental.neic.nordforsk.org#37]
We need to do something with the adjustment of the ratio.

**Comment by trz42** [comment]
Interesting issue. I changed window sizes a bit back and forth. It seems one to three columns are shown. For the images the following aspect ratios seem to be used. Three columns: 352:200 (~ 16:9), 293:200 (~ 3:2), 220:200 (~ 1:1). Two columns: 345:200 (~ 16:9), 354:200 (~ 16:9). One column: 344-735:200 (~ 16-33:9). The source files come with a diverse set of ratios (and sizes).

I believe, you need to settled on one or very small number of ratios (best would be one and fix it) and possibly a preferred actual size (in that one ratio) such that renderings look ok and also not too coarse grained. You may also shrink sizes of some images to reduce download times (minor issue).

16:9 seems to be a good ratio for two columns and three columns. For one column, you may consider a different layout (e.g., text floating around image or image left and some text to the right).

**Comment by yohell** [comment]
We probably need to make new thumbnails for a lot of the news articles, once we get the html/css fixes from the designers.

**Comment by bast** [comment]
Is this still an issue?

**Comment by yohell** [comment]
Not that I know.
