### ISSUE TITLE
Titles and photos in posts are repeated

### ISSUE THREAD

**Issue by bast** [neicnordic/experimental.neic.nordforsk.org#39]
Solution is to not repeat them in the post sources.

**Comment by bast** [comment]
Example: https://neic.no/news/2017/01/09/tomasz-malkiewicz-new-appointed-executive-manager/

**Comment by yohell** [comment]
Is it really? Do you always want to start with the photo? Should there only ever be a thumbnail, an no link to high resolution version?

**Comment by bast** [comment]
It's up to us to decide. I have created this issue to communicate that the repeated titles and images were not overlooked but are a known problem.

**Comment by yohell** [comment]
9759cc2 Nixing the new semantics for now, revering to previous where neither title nor thumbnail is repeated in template. Rather do it the old way (and not edit all the news articles to fit new semantics) and possibly redo it after the conference if we find that there's a better way to do it.
