### ISSUE TITLE
Link to wiki in menu broken

### ISSUE THREAD

**Issue by trz42** [neicnordic/experimental.neic.nordforsk.org#41]
Likely issue in _includes/header.html lines 38-39

**Comment by yohell** [comment]
Yes that is very likely the case :)

https://neic.nohttps//wiki.neic.no

@bast remind me, why don't we remove {{ site.baseurl }} from everything again?

**Comment by bast** [comment]
Without `{{ site.baseurl }}`I had problems with relative URLs from sub paths. But I think this was my fault. In short, there is probably no good reason for keeping them.
