### ISSUE TITLE
On the landing page replace real photos by nature photos

### ISSUE THREAD

**Issue by bast** [neicnordic/experimental.neic.nordforsk.org#42]
See the PHP prototype branch.

**Comment by yohell** [comment]
or actually no. Let's have the designers come up with a way to not distort the photos of people instead.

**Comment by bast** [comment]
@yohell you are working on this one, right? If yes, can you steal this issue from me? No problem if not, just want to make sure that we are not in a deadlock.

**Comment by yohell** [comment]
Executive decision: we do not replace news photos with random pieces of beautiful nature on the frontpage at this stage. Rationale: we need to get out of the situation where we depend on only a few Real Heroes to keep the website updated, and into a situation where people feel a sense of ownership of the information that gets posted about them. Replacing their face with a squirrel on the frontpage does not help this. We can revisit this issue after the conference if by then we feel that we'd rather have squirrels again, but for now the website is presentable and there's more important stuff to do.

**Comment by bast** [comment]
:+1:
