### ISSUE TITLE
Need a way to generate json for the api

### ISSUE THREAD

**Issue by yohell** [neicnordic/experimental.neic.nordforsk.org#5]
This is terrible `{{ site.activities | jsonify }}` because it includes attributes like "output".

**Comment by yohell** [comment]
This is one way to do it 52e8b1bfe39e9fb8bfc86a6156cb1088f95e2949. Good / bad?

**Comment by bast** [comment]
Looks good to me.

**Comment by bast** [comment]
API should be versioned so that when we change the API we don't break clients.

**Comment by yohell** [comment]
Versioned in 780371d30be21c74a6b59c592266d07db1b36939.
