### ISSUE TITLE
jonasholger@gmail.com

### ISSUE THREAD

**Issue by ambach** [neicnordic/experimental.neic.nordforsk.org#53]

**Comment by bast** [comment]
What is this supposed to be?

**Comment by ambach** [comment]
Sorry Radovan, pls cancel this.


I was just 'playing' around, no - actually looking for stuff like who has access to the training calendar, as one of my users (DeIC) wants to change an email account (Jonas Holger Hansen).



Best,

Anne-Marie







________________________________
Fra: Radovan Bast <notifications@github.com>
Sendt: 26. juni 2017 17:19
Til: neicnordic/neic.no
Cc: Anne-Marie Bach; Author
Emne: Re: [neicnordic/neic.no] jonasholger@gmail.com (#53)


What is this supposed to be?

-
