### ISSUE TITLE
Do not list both country and country code inside a person file

### ISSUE THREAD

**Issue by bast** [neicnordic/experimental.neic.nordforsk.org#6]
There is no doubt about "Norway" but there may be doubt about "NO" or "N". Also NO can be interpreted as false.

**Comment by bast** [comment]
Is it "SE"? Or "S"? Again, no doubt about "Sweden".

**Comment by bast** [comment]
I agree now that country codes look better on page overviews. But we want to get rid of the redundancy in person data pages.

**Comment by yohell** [comment]
Sure, I only included both so you would have the ability to easily A/B compare and see for yourself. 

Way forward (I think) is to put assign country code in "country" and drop country_code. And (possibly) template our way to full country names where suitable (which I guess is the person page only?).

**Comment by yohell** [comment]
Fixed in b579777c90cc9b7d3a50d6ba70e2055192a148a8.
