### ISSUE TITLE
Make sure that events render locally

### ISSUE THREAD

**Issue by bast** [neicnordic/experimental.neic.nordforsk.org#64]
When running site locally on http://127.0.0.1:4000/, events seem to be always empty. It looks like the calendar is then not loaded at all.

**Comment by yohell** [comment]
Actually I didn't mean to self-assign this. But this is a rather trivial config setting on google calendar. we can set it to also allow serving the calendar to pages hosted at localhost if we want to. and likewise to *.github.io so forks display right. I don't know what the drawbacks are, if any. That people may be rednering our calendar on pages that aren't ours? idk if we care about that.

**Comment by yohell** [comment]
Correction: this should be a trivial conf issue on google calendar, but in reality it is far from intuitive. The docs are extremely sparse, and the error message isn't super helpful. I've tried every conf setting I can think of, and I still don't understand what in the present conf causes this to work on eg neic.no and not on localhost or yohell.github.io. The "it may take up to 5min to take effect" for config changes certainly doesn't help speed up test cycles either. If anyone else wants to give this a stab please feel welcome. It should be as easy as creating an API key (specifically a browser key) and setting it to accept the right referrers.

**Comment by yohell** [comment]
I've changed access rights on that API key now so it should allow rendering on github forks (*.github.io/*). Please let me know if that's bad for some reason. Also events should have always rendered correct on localhost? Maybe the issue at the time was that noone had actually added any events to the calendar? @caela I hear that you are the original requestor. Could you please validate that it works for you?

**Comment by yohell** [comment]
No reply and works for me.
