### ISSUE TITLE
Frontpage list of current activities should have link to past activities

### ISSUE THREAD

**Issue by yohell** [neicnordic/experimental.neic.nordforsk.org#72]
If I go to neic.no and try to find an activity that is now closed, I can't find it under the heading ACTIVITIES which is in plain sight, but I have to know that I have to (discover that there is a menu top right, click it to expand it, and then) click the menu item with the same name as the heading that didn't have what I wanted.

**Comment by yohell** [comment]
Related to https://github.com/neicnordic/neic.no/issues/73.

**Comment by bast** [comment]
Closing since issue is over 4 years old.
