### ISSUE TITLE
Get rid of hamburger menu

### ISSUE THREAD

**Issue by yohell** [neicnordic/experimental.neic.nordforsk.org#73]
Adding this based on feedback from Juha

"""However i don't like hamburger menu, i think that they are very last season and were designed for the mobile but didn't work well there either: https://www.google.es/search?client=safari&rls=en&q=why+hamburger+menus+are+bad&ie=UTF-8&oe=UTF-8&gfe_rd=cr&dcr=0&ei=1K0WWrP1AvOs8wfRqIjwAw

e.g. "Summary: Discoverability is cut almost in half by hiding a website’s main navigation. Also, task time is longer and perceived task difficulty increases." - https://www.nngroup.com/articles/hamburger-menus/

**Hamburger Menus and Hidden Navigation Hurt UX Metrics**
Discoverability is cut almost in half by hiding a website’s main navigation. Task time is longer and perceived task difficulty increases.
"""
Related to https://github.com/neicnordic/neic.no/issues/72

**Comment by bast** [comment]
Closing since issue is over 4 years old and does not seem to have bothered others enough.
